_BASE_: ../../ade20k/semantic-segmentation/maskformer2_R50_bs16_160k.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 6
DATASETS:
  TRAIN: ("synthetic_scene_sem_seg_train",)
  TEST: ("synthetic_scene_sem_seg_val",)
INPUT:
  DATASET_MAPPER_NAME: "synthetic_scene_batch"
  SYNTHETIC_SCENE:
    WIDTH: 512
    HEIGHT: 512
    SEED: 1234
    TEST_SEED: 4321
    TEST_SAMPLES: 1000
    TEST_BATCH_SIZE: 4
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 0
TEST:
  EVAL_PERIOD: 500